name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0-259.8.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  features:
    path: ..
  shared_preferences: ^2.0.0-nullsafety

flutter:
  uses-material-design: true
