name: features
description: A Flutter package to help manage features enabled/disabled for a user
version: 1.0.0+1
homepage: https://github.com/rodydavis/features

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
