name: features
description: A Flutter package to help manage features enabled/disabled for a user
version: 1.1.0-nullsafety
repository: https://github.com/rodydavis/features
homepage: https://github.com/rodydavis/plugins

environment:
  sdk: '>=2.12.0-259.8.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
